services:
  nginx:
    image: nginx:latest
    depends_on:
      - symfony
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public

  symfony:
    build:
      context: ./docker/symfony
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:latest
    ports:
      - "8990:5432"
    environment:
      POSTGRES_PASSWORD: "pwd"
      POSTGRES_DB: "kiranico"
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata: {}
